nf_core_version: 2.14.1
repository_type: pipeline
template:
  author: Lea Picard
  description: This pipeline retrieves orthologous gene sequences and construct codon-aware
    analyses and phylogenetic trees
  force: true
  is_nfcore: true
  name: genephylo
  org: nf-core
  outdir: .
  version: 1.0.0dev
